const GET_ALL_POSTS_REQUEST = 'GET_ALL_POSTS_REQUEST';
const GET_ALL_POSTS_SUCCESS = 'GET_ALL_POSTS_SUCCESS';
const GET_ALL_POSTS_FAIL = 'GET_ALL_POSTS_FAIL';

export { GET_ALL_POSTS_REQUEST, GET_ALL_POSTS_SUCCESS, GET_ALL_POSTS_FAIL };
