const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
const GET_USERS_FAIL = 'GET_USERS_FAIL';

export { GET_USERS_REQUEST, GET_USERS_SUCCESS, GET_USERS_FAIL };
